stages:
  - qa
  - build
  - deploy

variables:
  CI_NODE_INDEX: "0"
  SHELL: "/bin/bash"

default:
  image: node:18
  cache:
    key:
      files:
        - frontend/package-lock.json
      prefix: npm
    paths:
      - frontend/node_modules/

test:unit:
  stage: qa
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test

build:
  stage: build
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build
  cache:
    paths:
      - frontend/dist
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 60 mins
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:s3:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - "/usr/bin/env"
  script:
    - cd frontend
    - export AWS_DEFAULT_REGION=eu-west-2
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws s3 sync dist/ s3://$S3_BUCKET
    # https://stackoverflow.com/a/37752872/9713831 - clear CloudFront cache
    - aws cloudfront create-invalidation --distribution-id=ED87W9YWEWNCM --paths /
  # rules:
  #   - if: '$CI_COMMIT_REF_NAME == "main"'
  #     when: always
